# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenSCD Architecture
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pascalwilbrink.github.io" # the base hostname & protocol for your site
collections_dir: collections

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

collections:
  guides:
    output: true
  plugins:
    output: true
  components:
    output: true

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
